spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.76/seil?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

  jpa:
    show-sql: true

  #全局配置，将对象为空时，属性不返回，当如果为空依旧要返回，需要独自给初始化并注释下列注解
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    #设置日志输出的格式，减少输出的信息长度
#    console: "%d - %msg%n"
#  path: d:\\springlog

wechat:
  mpAppId: wx7ed8085780363b9d
  mpAppSecret: 1b27c02bda115ab4e01908973c30d817


