spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.32/seil?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    #设置日志输出的格式，减少输出的信息长度
#    console: "%d - %msg%n"
#  path: d:\\springlog
